apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-flask-hello-hpmb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-flask-hello-hpmb
    app.kubernetes.io/part-of: p
  name: python-flask-hello-hpmb
  namespace: burrzinga-hac-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: python-flask-hello-hpmb
    weight: null
status: {}
