apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-flask-hello-hpmb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-flask-hello-hpmb
    app.kubernetes.io/part-of: p
  name: python-flask-hello-hpmb
  namespace: burrzinga-hac-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: python-flask-hello-hpmb
status:
  loadBalancer: {}
